#!/bin/bash

echo "-----"
echo "Reinstalling dependent packages in vendor/"
if [ -d vendor/ ]; then
    rm -rf vendor/
fi
echo "-----"

composer install --quiet
echo "Reinstalled"

echo "-----"
if [ ! -f .env ]; then
    echo "Setting file .env is not found, Copying from .env.example ."
    cp .env.example .env
    php artisan key:generate
    echo "A new APP_KEY in .env generated by artisan."
else
    echo '.env exist.'
fi

echo "-----"
